---
resources:
- name: solder
  type: git
  source:
    uri: "https://github.com/venkatpathy/solder"
    branch: master

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: solder
  - task: build
    file: solder/ci/build.yml
    params:
      PROJECT_TYPE: GRADLE