---
resources:
- name: solder
  type: git
  source:
    uri: "https://github.com/venkatpathy/solder"
    branch: master

jobs:
- name: build
  plan:
  - get: solder
    trigger: true
  - task: build
    file: solder/ci/build.yml